# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://kevinxuv.github.io/
# baseurl: /
title: Kevin Xu
author: Kevin Xu
description: Personal blog
avatar: avatar.jpg
email: kevin.xu.v@gmail.com
github: kevinxuv # username
# twitter: username
linkedin: kevinxuv
stackoverflow: 2593783   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
